name: Generate Snake Animation

on:
  push:
    branches:
      - output  # Triggers on changes to the "output" branch
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Generate the snake animation
      - name: Generate Snake animation
        uses: Platane/snk@master
        with:
          github_user_name: SadmanSakibShuvo1  # Your GitHub username
          outputs: dist/github-contribution-grid-snake.svg

      # Step 3: Commit and push the generated SVG
      - name: Commit and push the animation
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generated snake animation"
          git push origin output
