name: Generate Snake Animation

on:
  push:
    branches:
      - output  # Ensure this matches your branch name
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake animation
        uses: Platane/snk@master
        with:
          github_user_name: SadmanSakibShuvo1
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and push the animation
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generated snake animation"
          git push
